services:
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Paris
    volumes:
      - ./config/jackett:/config
      - ./downloads:/downloads
    ports:
      - "9117:9117"
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Paris
    volumes:
      - ./config/radarr:/config
      - ./downloads:/downloads:rw
      - ./movies:/movies:rw
    ports:
      - "7878:7878"
    restart: unless-stopped

  plex:
    image: linuxserver/plex
    container_name: plex
    environment:
      - PUID=0
      - PGID=0
      - VERSION=docker
      - TZ=Europe/Paris
      - PLEX_CLAIM=${PLEX_CLAIM:-claim-xxxxxxx}
    volumes:
      - ./config/plex:/config
      - ./movies:/movies
      - ./series:/series
    ports:
      - "32400:32400"
    restart: unless-stopped